os: windows
language: csharp
solution: MouseKeyHook.sln
mono: none
script:
- choco install dotnetcore-sdk

- powershell -c "Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Scope LocalMachine"
- powershell -c "Import-Module PackageManagement; Install-PackageProvider Nuget"
- powershell -c "Import-Module PackageManagement; Register-PackageSource -Name NuGetOrg -Location https://www.nuget.org/api/v2 -ProviderName NuGet"
- powershell -c "Import-Module PackageManagement; Install-Package -Source NuGetOrg -Name NuGet.CommandLine -Force -ExcludeVersion -Destination C:\tools"

- /c/tools/NuGet.CommandLine/tools/nuget sources list

- dotnet --version
- dotnet restore -v n
